sudo: false
language: c

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: UerIE3HwG5wNyEYjo/79MqqxQu90Txt1yKyipXvc81dw1blBU37ew8xcGsVxcFH3/UxHeFGytoFFzAagkCYktKbQ454o4LQd2wSNIqZWDRGMb21xFcH0WOJRAZG8onC1ntRssDK9st6hntbl+EKiUw/6QFih5UXFis6RGHFOyBVWm/SDPAtSjODpxVcYKWs+HIkwKlSZhl+8ZS6Z8xFtxmJCeqFSiC/nERINyrdKs9xSuPckhadYk0dJI5tgDxhwHRBHH3EC/cl7H0jDjlk2N/aU35Kb82bbps3uor0TbYA/HyLSXxVG6cbQsOJkRqmkGVkI2KpWGf+5ZXS7M8feObZxUZk3tsqJiq/15HIlglLYJWwbvUwQnadq4sGLoQNcJPjgfRbZKD5S275VB0IThsP5mBOPM4Lz1XrWNMYFIO+ML1ffMIsgsPe0jk5hrP0Q15aQcBuOowVvDH+HUnkI9inm6PtNLMqObfpFy9XS9q9UNvLmjJe1N0t2qwi1+WMCYiCeg/n9Dd4G9Npu2Q7z8czbis70Z/7XswReBYGgxp3TPBV5sTDYaUsyqdnWCvJYKiRsyKkMoXzeuHFEbq/ypcdJBBUOaq3LGEOnysHX0e5owWpENJ4PhXVDcwWUX+/4v/3uofoq9lRBlX26dtZ/eCBosRW8Qfql924MJ5DCKow=
  - secure: JzRQMhQq/IeT87GKtA+/BhBVYxeQ9CnXs388nH/XzYFyN7ePgvI6SeGVNNon8FUys6U+zxRg+7NPBr5kqZC0zBWiIGchRifNgvOtebdPRAFd74SToWFzhgO3mjLDznvnOpx32pGwWehzLkl/V9T8LXO/xn/JOkG0/qkVZrrvRKugkZCnQsQ+s7JnwqL/hcQ88EVSSrcgpDGLmWGbjZrXo0utjdluoFxAMHg9oMjyOcIMY4egulZZ2MhLjewJ3z7pmtnIUp8qy76do0Doqt0BbEi6TtcEkdXIl77ep9eZaJF2J7ieyhAMvfTqMMyuGz1QkOEvIS6vt100QCTy70qy0e14tN1cBd37YwTE4k2xm3HuUI/xS9BuW5gSpL91sDWF3MMKhgA4ZAMZGacq2neEv22VlEkdKueMPoBvuHQWHMp9XqSMdJPjllf4PQD/6gY6QFwrsqHaHEtqrxMYyLBuIXAoblWmxkDVruEDJLYiF1yh6oae6WkBGmyteUYCLceoWjZruBmzs0cIGFXv3faeV2KkCIY3RkNbQTbI69+N/caaB4hc6az3rZw/q3475Y0wWbUOLZbboLr1LQUfPBeMiwBYQIfAMZL8WUGRIkJxDOXYdkzXv6Qnbu7McuvcB+GI8rRGOQsBUPOnB+rJrL3f2+RHJCaJKkvH0lQSgVCOT8c=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - secure: HzVLXvfG1+bavNoOWfkcKi0mQA18IK2qBO+yYi7raALd52E0gejvi/aIQtRvStVRzd3yoMQTwz2/eUghS2TujZhWLBKNY6Se1udR+hp7ROD+RNZnJCPodBnqXB+k2Qa+O+XMHtvzpHkt8EaajCXzGtYmaPJb/3X5QdpSwk/khYKpzu6hFk8gpY1Me2F3QqD2E3NUmHbenMIiGqB1NbotizvGPWdDO6IKTJVSfgZq5mJ/15sLI0Y7NBsRXQt4Cag++D/k+zKuTfzDM6Lcs7XYDbTjwv3sSSYLNjN7ybKdvVswHXBUXNNKwCGM/wQ+7DzBoNxMYkewh49P0Y0biD4QKe4lOuTCjgY8NO6TymE3ccCj2eJRKFRVgoX2JE2wmYB7ASj4UetN4cXuqH3vP6kZppCXS72aysAwnpcviijAqm6v4dT8/aOw6I7lGACko0M8tiOMpCTmDl6v1rrFzxxOHDjQQlJIp9vO0DdU7fRqQae4lBvEKX7Zk4nqeU0qzAMbIhzjhnvRnVH/M0SarP7WyZU1SMMg/azv0AtJn8QrxolyghPdY+nLwnlGGjUyVhmAvVfOqanQnjnvFO07z+34J9HmlF6P/JyG/XfkWEFLollU13Lpb5qow+DjoXWcnCKqHfKlDYCgKfnwydvvgyv1muHpqayhXrXQPJb4xJjN110=
